# Generated by Django 5.2.8 on 2025-11-15 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeaReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='評価')),
                ('content', models.TextField(blank=True, verbose_name='レビュー内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('tea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tea.tea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tea_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'レビュー',
                'verbose_name_plural': 'レビュー一覧',
                'unique_together': {('user', 'tea')},
            },
        ),
    ]
