# Generated by Django 5.2.8 on 2025-11-22 08:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0005_auto_20251122_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='メール確認トークン'),
        ),
    ]
