# Generated by Django 5.2.8 on 2025-11-24 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0006_alter_user_email_verification_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritetea',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='favoritetea',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='favoritetea',
            table='favorite_teas',
        ),
        migrations.AlterModelTable(
            name='tea',
            table='teas',
        ),
        migrations.AlterModelTable(
            name='teareview',
            table='tea_reviews',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
