# Generated by Django 5.2.8 on 2025-11-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0007_alter_favoritetea_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
