# Generated by Django 5.2.8 on 2025-11-27 01:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='お茶名')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('steam_type', models.CharField(choices=[('light', '浅蒸し'), ('middle', '中蒸し'), ('deep', '深蒸し')], max_length=20, verbose_name='蒸し度')),
                ('origin', models.CharField(blank=True, max_length=100, verbose_name='産地')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('caffeine_free', models.BooleanField(default=False, verbose_name='カフェインレス')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='公開日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'db_table': 'teas',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, help_text='管理者用のユーザー名', max_length=150, null=True, unique=True, verbose_name='ユーザー名(管理者用)')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('nickname', models.CharField(blank=True, help_text='一般ユーザー用のユーザー名', max_length=30, verbose_name='ユーザー名(一般ユーザー用)')),
                ('is_email_verified', models.BooleanField(default=False, help_text='メールアドレスが確認されているかどうか', verbose_name='メール確認済み')),
                ('email_verification_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='メール確認トークン')),
                ('email_verification_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='確認メール送信日時')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='FavoriteTea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_teas', to=settings.AUTH_USER_MODEL)),
                ('tea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='model.tea')),
            ],
            options={
                'db_table': 'favorite_teas',
            },
        ),
        migrations.CreateModel(
            name='TeaReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], verbose_name='評価')),
                ('content', models.TextField(blank=True, verbose_name='レビュー内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('tea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='model.tea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tea_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'レビュー',
                'verbose_name_plural': 'レビュー一覧',
                'db_table': 'tea_reviews',
                'unique_together': {('user', 'tea')},
            },
        ),
    ]
