# Generated by Django 5.2.8 on 2025-11-30 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.IntegerField(verbose_name='送料(円)')),
                ('free_shipping_threshold', models.IntegerField(blank=True, help_text='この金額以上で送料無料。設定しない場合は常に送料がかかります', null=True, verbose_name='送料無料の金額(円)')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('start_date', models.DateField(verbose_name='適用開始日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'verbose_name': '送料設定',
                'verbose_name_plural': '送料設定',
                'db_table': 'shipping_fees',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, help_text='例: 10.00 (10%の場合)', max_digits=5, verbose_name='税率(%)')),
                ('start_date', models.DateField(verbose_name='適用開始日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'verbose_name': '消費税率',
                'verbose_name_plural': '消費税率',
                'db_table': 'tax_rates',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'カート',
                'verbose_name_plural': 'カート',
                'db_table': 'carts',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='注文番号')),
                ('status', models.CharField(choices=[('pending', '支払い待ち'), ('paid', '支払い完了'), ('processing', '処理中'), ('shipped', '発送済み'), ('delivered', '配達完了'), ('cancelled', 'キャンセル')], default='pending', max_length=20, verbose_name='ステータス')),
                ('subtotal', models.IntegerField(verbose_name='小計(税抜)')),
                ('tax_amount', models.IntegerField(verbose_name='消費税額')),
                ('shipping_fee', models.IntegerField(verbose_name='送料')),
                ('total_amount', models.IntegerField(verbose_name='合計金額(税込)')),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='適用税率(%)')),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=200, verbose_name='Stripe Checkout Session ID')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200, verbose_name='Stripe Payment Intent ID')),
                ('shipping_name', models.CharField(max_length=100, verbose_name='配送先名')),
                ('shipping_postal_code', models.CharField(max_length=8, verbose_name='郵便番号')),
                ('shipping_address', models.CharField(max_length=200, verbose_name='住所')),
                ('shipping_phone', models.CharField(max_length=20, verbose_name='電話番号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注文日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '注文',
                'verbose_name_plural': '注文',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeaProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(choices=[(100, '100g'), (200, '200g'), (300, '300g')], verbose_name='重量(g)')),
                ('price', models.IntegerField(verbose_name='価格(円・税抜)')),
                ('stock', models.IntegerField(default=0, verbose_name='在庫数')),
                ('is_available', models.BooleanField(default=True, verbose_name='販売中')),
                ('tea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='model.tea', verbose_name='お茶')),
            ],
            options={
                'verbose_name': 'お茶商品',
                'verbose_name_plural': 'お茶商品',
                'db_table': 'tea_products',
                'ordering': ['tea', 'weight'],
                'unique_together': {('tea', 'weight')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('price', models.IntegerField(verbose_name='単価(税抜)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='model.order', verbose_name='注文')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.teaproduct', verbose_name='商品')),
            ],
            options={
                'verbose_name': '注文明細',
                'verbose_name_plural': '注文明細',
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='追加日時')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='model.cart', verbose_name='カート')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.teaproduct', verbose_name='商品')),
            ],
            options={
                'verbose_name': 'カート明細',
                'verbose_name_plural': 'カート明細',
                'db_table': 'cart_items',
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
